# Site
name: "北美嘉哥"
title: "北美嘉哥"
description: "不积跬步，无以至千里；不积小流，无以成江海。"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'a89426115w132653071p136636180'
disqus: junjia
mailchimp-list: 'https://gmail.us1.list-manage.com/subscribe/post?u=6280987e6139b54eccd331775&amp;id=87185722b1'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  admin:
    name: admin
    display_name: 北美嘉哥
    #gravatar: e56154546cf4be74e393c62d1ae9f9d4
    #email: wowthemesnet@gmail.com
    web: junjia.me
    #twitter: https://twitter.com/wowthemesnet
    description: "No comments."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 24
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
